name: npm build, lint, test and publish

on: [push]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm run test
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ${{ secrets.USER_NAME }}
        HOST: ${{ secrets.HOST }}
        SCRIPT: ${{ secrets.SCRIPT }}
        KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
